### ISSUE TITLE
Relation between dimensions

### ISSUE THREAD

**Issue by ktk** [zazuko/rdf-cube-schema-viz#15]
For use-cases like precision we need to be able to express that two dimensions are related with each other and what the relation between the two dimensions is.

This should be a property or maybe even a path if the relation is more complex.

**Comment by ktk** [comment]
See image in #16 for an example usage.

**Comment by Rdataflow** [comment]
could you give us an example on how #16 can be solved? that would be great and helpful to understand how to implement such cases and design the API for visualize. thx

**Comment by ktk** [comment]
@Rdataflow I finished the model with @bergos and will write it down now. We want to document the thinking process behind the model so it takes some time to write that down properly. I hope to finish it by tomorrow.

**Comment by ktk** [comment]
Can be found here now https://github.com/zazuko/rdf-cube-schema-viz#solution

**Comment by semanticfire** [comment]
Given an observation in  [RDF Cube Schema](https://github.com/zazuko/rdf-cube-schema) that defines multiple quantitative values (dimensions). It should be possible to express that there is a relation between two quantitative values..

### Problem & Approach

Given:

```turtle
<observation1> a Observation
<observation1> <value> 123.45
<observation1> <precision> 0.017
```

We want to express that an observation has a `<value>` and `<precision>` is the precision of `<value>`.

A standard reification/annotation approach would look like this in RDF

```turtle
# reification
<statement>
  <subject> <observation1>
  <predicate> <value>
  <object> 123.45

<statement> <precision> 0.017
```

On large datasets this would have a significant impact on query performance as it would require joins to get the `<precision>` of a particular `<value>` . In other words, it is not suitable for Cubes with many observations. It also makes the model more complicated to understand. 

A simplified approach would be to model quantitative values as entities, for example:

```
# simplified reification
<observation1> <value> [
    <value> 123.45;
    <precision> 0.017;
]
```

This is easier to understand due to forward-linking but it puts the value itself on an additional entity and thus requires a join per observation to fetch the value and its precision. 

The "new" approach would be to use RDF*:

```turtle
# RDF*
<observation1> <value> "123.45" 
<<<observation1> <value> "123.45">> <precision> 0.017
```

This is nice to read and write but it is too early to require that as support for it is relatively new. We also assume it does have performance impacts on triplestores if we would query that.

### Solution

Our approach moves the reification/annotation to the [constraint](https://github.com/zazuko/rdf-cube-schema#metadata-and-validation-constraint) of the cube, in particular to its dimension. There is one `sh:property` definition per dimension so the lookup only needs to be done once and is valid for all observations of that particular cube. 

```turtle
[ 
  sh:path <dimension/precision>
  # ... additional definitions for that sh:property
  cube:relation [ a cube:Relation ;
     # for the moment we recommend to define properties in your own namespace,
     # thus the "ex" namespace.
     # We might try to get that into another vocab like QUDT in the future or
     # provide generic properties on our own
     ex:precisionOf <dimension/value>
  ]
]
```

We define a `<relation>` for the cube dimension `<precision>`. The `<relation>` is of type `<PropertyRelation>`. It's `<target>` is the property `<value>`.

This approach is very generic and allows to express other relations as well, for example aggregations. Given the following triples:

```turtle
<observation1> a Cube
<observation1> <population> 10
<observation1> <populationMale> 7
<observation1> <populationFemale> 3
```

We want to express that `<population>` is the sum of` <populationMale>` and `<populationFemale>`. 

```turtle
[
  sh:path <populationMale>
  <relation> [ <AddRelation>
    <target> <population>
  ]
], [
  sh:path <populationFemale>
  <relation> [ <AddRelation>
    <target> <population>
  ]
]
```

The same semantics could be expressed the other way around:

```turtle
[
  sh:path <population>
  <relation> [ <SumRelation>
    <source> <populationMale>, <populationFemale>
  ], [ <SumRelation>
    <source> <populationAge0050>, <population5090> # restrictions on instances of a particular dimension
  ]
]
```

This is obviously advanced usage of the cube and increases its complexity. But it gives the expressiveness needed to describe complex relationship between data in a machine processable way.
